{% set name = "pyhdfe" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8cddc5f5a09148d3281fca3c787146a85ecc5a7517be3ae5762bfe507907b7fb

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy >=1.17
    - scipy >=1.0
test:
  imports:
    - pyhdfe
    - pyhdfe.algorithms
    - pyhdfe.interface
    - pyhdfe.utilities
    - pyhdfe.version
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/jeffgortmaker/pyhdfe
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Algorithms for absorbing high dimensional fixed effects.
  doc_url: https://pyhdfe.readthedocs.io/
  dev_url: https://github.com/jeffgortmaker/pyhdfe

extra:
  recipe-maintainers:
    - bashtage
